id: PDB0C8CCF
initial_creation_type: input
source_metadata:
  title: Dzogchen Pema Rigdzin Series
  language: en
  description: Texts by Dzogchen Pema Rigdzin (rdzogs chen padma rig 'dzin, 1625–1697),
    the great adept who founded Dzogchen Monastery in Kham.
  volume:
    82514f3124ec47fb81fdc16a50795c99:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
created_at: '2022-02-28T23:11:42.476523'
last_modified_at: '2022-02-28T23:11:42.476529'
